- hosts: exercises
  vars_files:
    - secrets.yml
  tasks:
    - name: "Pull changes from GitHub"
      git:
        repo: "{{ repository }}"
        dest: "{{ directory }}"
        version: master
        accept_hostkey: yes
      register: repo

    - name: "Install Composer dependencies"
      shell: "composer install --no-scripts"
      args:
        chdir: "{{ directory }}/backend"
      when: repo.changed

    - name: "Cache the configuration"
      shell: "php artisan config:cache"
      args:
        chdir: "{{ directory }}/backend"
      when: repo.changed

    - name: "Clear the view cache"
      shell: "php artisan view:clear"
      args:
        chdir: "{{ directory }}/backend"
      when: repo.changed

    - name: "Run the migrations"
      shell: "php artisan migrate --force"
      args:
        chdir: "{{ directory }}/backend"
      when: repo.changed

    - name: "Compile frontend"
      shell: "npm run build"
      args:
        chdir: "{{ directory }}/frontend"
      when: repo.changed

    - name: "Restart server"
      shell: "pm2 restart Exercises"
      args:
        chdir: "{{ directory }}/frontend"
      when: repo.changed
