- hosts: exercises
  vars_files:
    - secrets.yml
  tasks:
    - name: "Pull changes from GitHub"
      git:
        repo: "{{ repository }}" # This is how we can make this step reusable across projects
        dest: "{{ directory }}"
        version: master # Branch to pull
        accept_hostkey: yes
      register: repo # Store the result of this task in a variable

    - name: "Install Composer dependencies"
      shell: "composer install --no-scripts --no-dev"
      args:
        chdir: "{{ directory }}"
      when: repo.changed # Only run this step if we actually pulled new changes from GitHub

    - name: "Cache the configuration"
      shell: "php artisan config:cache"
      args:
        chdir: "{{ directory }}"
      when: repo.changed # Only run if we pulled changes

    - name: "Clear the view cache"
      shell: "php artisan view:clear"
      args:
        chdir: "{{ directory }}"
      when: repo.changed # Only run if we pulled changes

    - name: "Run the migrations"
      shell: "php artisan migrate --force"
      args:
        chdir: "{{ directory }}"
      when: repo.changed # Only run if we pulled changes

    - name: "Compile frontend"
      shell: "npm run prod"
      args:
        chdir: "{{ directory }}"
      when: repo.changed # Only run if we pulled changes
